# Generated by Django 5.0.6 on 2024-06-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_layer_layer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('Coating Layer', 'Coating Layer'), ('Surface Treatment', 'Surface Treatment')], default='Coating Layer', max_length=100),
        ),
    ]
