# Generated by Django 5.0.6 on 2024-06-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_layer_layer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='coating_method',
            field=models.CharField(blank=True, choices=[('Spin Coating', 'Spin Coating'), ('Thermal Evaporation', 'Thermal Evaporation'), ('Screen Printing', 'Screen Printing'), ('Infilteration', 'Infilteration')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_role',
            field=models.CharField(blank=True, choices=[('ETL', 'ETL'), ('Active Layer', 'Active Layer'), ('HTL', 'HTL'), ('Top Contact', 'Top Contact'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
