# Generated by Django 5.0.6 on 2024-07-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_layer_coating_method_slotdiecoating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotdiecoating',
            name='coating_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotdiecoating',
            name='coating_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotdiecoating',
            name='meniscus_guide_tab_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotdiecoating',
            name='meniscus_guide_thickness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotdiecoating',
            name='pump_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotdiecoating',
            name='shim_thickness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotdiecoating',
            name='slot_die_and_substrate_gap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotdiecoating',
            name='wet_film_thickness',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
