# Generated by Django 5.0.6 on 2024-07-29 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_slotdiecoating_coating_speed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coatingparameters',
            name='infilteration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.infiltration'),
        ),
        migrations.AlterField(
            model_name='coatingparameters',
            name='screen_printing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.screenprinting'),
        ),
        migrations.AlterField(
            model_name='coatingparameters',
            name='slot_die_coating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.slotdiecoating'),
        ),
        migrations.AlterField(
            model_name='coatingparameters',
            name='spin_coating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.spincoating'),
        ),
        migrations.AlterField(
            model_name='coatingparameters',
            name='thermal_evaporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.thermalevaporation'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='coating_method',
            field=models.CharField(blank=True, choices=[('Spin Coating', 'Spin Coating'), ('Thermal Evaporation', 'Thermal Evaporation'), ('Screen Printing', 'Screen Printing'), ('Infilteration', 'Infilteration'), ('Slot Die Coating', 'Slot Die Coating'), ('Doctor Blade Coating', 'Doctor Blade Coating')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DoctorBladeCoating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Doctor Blade Coating',
            },
        ),
        migrations.AddField(
            model_name='coatingparameters',
            name='doctor_blade_coating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.doctorbladecoating'),
        ),
    ]
