# Generated by Django 5.0.6 on 2024-08-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_coatingparameters_doctor_blade_coating'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='stacks',
            field=models.ManyToManyField(related_name='layers', to='app.stack'),
        ),
    ]
