# Generated by Django 5.0.6 on 2024-08-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_copy_fk_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='stack',
        ),
    ]
