# Generated by Django 5.0.6 on 2024-08-12 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_layer_stack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='coating_method',
            field=models.CharField(blank=True, choices=[('Spin Coating', 'Spin Coating'), ('Thermal Evaporation', 'Thermal Evaporation'), ('Screen Printing', 'Screen Printing'), ('Infilteration', 'Infilteration'), ('Slot Die Coating', 'Slot Die Coating'), ('Doctor Blade Coating', 'Doctor Blade Coating'), ('Spray Pyrolysis', 'Spray Pyrolysis')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SprayPyrolysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Spray Pyrolysis',
            },
        ),
        migrations.AddField(
            model_name='coatingparameters',
            name='spray_pyrolysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.spraypyrolysis'),
        ),
    ]
