# Generated by Django 5.0.6 on 2024-08-21 14:24

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='jv_software',
            field=models.CharField(choices=[('default', 'default'), ('new', 'new')], default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.user_directory_path),
        ),
    ]
