# Generated by Django 5.0.6 on 2024-08-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_stack_jv_software_alter_userprofile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coatingparameters',
            old_name='infilteration',
            new_name='infiltration',
        ),
        migrations.AlterField(
            model_name='layer',
            name='coating_method',
            field=models.CharField(blank=True, choices=[('Spin Coating', 'Spin Coating'), ('Thermal Evaporation', 'Thermal Evaporation'), ('Screen Printing', 'Screen Printing'), ('Infiltration', 'Infiltration'), ('Slot Die Coating', 'Slot Die Coating'), ('Doctor Blade Coating', 'Doctor Blade Coating'), ('Spray Pyrolysis', 'Spray Pyrolysis')], max_length=100, null=True),
        ),
    ]
