# Generated by Django 5.0.6 on 2024-09-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_experimentpost_experimentcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentstatus',
            name='has_jv_files',
            field=models.BooleanField(default=False),
        ),
    ]
